project_id = "gvroklegcmxsqdcascvp"

[functions.send-approval-notification]
verify_jwt = false

[functions.notify-job-application]
verify_jwt = false

[functions.submit-external-application]
verify_jwt = false

[functions.send-birthday-notifications]
verify_jwt = false

[functions.send-greeting-card]
verify_jwt = false

[functions.send-leave-notification]
verify_jwt = false

[functions.send-schedule-notification]
verify_jwt = false
